### ISSUE TITLE
Extend ESI introspection to include GPU information

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#531]
In the long-term, automatic identification of GPU nodes and their associated traits will be valuable for users that have specific GPU requirements. Updating baremetal introspection to handle that will be very valuable.

**Comment by tzumainn** [comment]
Actually, looks like this exists. Here are the steps:

a) Create an `accelerators.yaml` file and place it in /etc/ironic-inspector

```
pci_devices:
  - vendor_id: "10de"
    device_id: "1eb8"
    type: GPU
    device_info: NVIDIA Corporation Tesla T4
  - vendor_id: "10de"
    device_id: "1df6"
    type: GPU
    device_info: NVIDIA Corporation GV100GL
  - vendor_id: "10de"
    device_id: "20b0"
    type: GPU
    device_info: NVIDIA Corporation GA100
```

b) Update ironic-inspector.conf and restart the service

```
[accelerators]
known_devices=/etc/ironic-inspector/accelerators.yaml
.
.
.
[processing]
processing_hooks=$default_processing_hooks,extra_hardware,lldp_basic,local_link_connection,physnet_cidr_map,accelerators
```

c) Update ironic.conf and restart `ironic_conductor`

```
[inspector]
extra_kernel_params = ipa-inspection-collectors=default,pci-devices
```
